### ISSUE TITLE
The WakaTimePackage package did not load correctly

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/ssms-wakatime#31]
```
SSMS 18 version: 2019.150.18390.0 (Microsoft Visual Studio 2017 version: 15.0.28307.421)
```

`CreateInstance failed for package [WakaTimePackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;file:///c:\program files (x86)\microsoft sql server management studio 18\common7\ide\extensions\wakatime.v18\WakaTime.dll&apos; or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)&#x000D;&#x000A;System.IO.FileLoadException: Could not load file or assembly &apos;file:///c:\program files (x86)\microsoft sql server management studio 18\common7\ide\extensions\wakatime.v18\WakaTime.dll&apos; or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)&#x000D;&#x000A;File name: &apos;file:///c:\program files (x86)\microsoft sql server management studio 18\common7\ide\extensions\wakatime.v18\WakaTime.dll&apos; ---&gt; System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.`

**Comment by mabubakarriaz** [comment]
Having same issue. which .net framework is need to run this extension?

**Comment by odskee** [comment]
Was running into the same issue; error directed to https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/ee890038(v=vs.100)?redirectedfrom=MSDN

If you run into this problem, you need open the WakaTime.v18 directory within SMSS Extensions and make sure all files have been unblocked (right click -> properties).  Then start SMSS as Admin, you can enter the API key from Tools -> WakaTime -> Settings but should be set if already using VS.

**Comment by webmasterrm** [comment]
> Was running into the same issue; error directed to https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/ee890038(v=vs.100)?redirectedfrom=MSDN
> 
> If you run into this problem, you need open the WakaTime.v18 directory within SMSS Extensions and make sure all files have been unblocked (right click -> properties). Then start SMSS as Admin, you can enter the API key from Tools -> WakaTime -> Settings but should be set if already using VS.

This solution works for me! :-)

**Comment by ricardosuab93** [comment]
> Was running into the same issue; error directed to https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/ee890038(v=vs.100)?redirectedfrom=MSDN
> 
> If you run into this problem, you need open the WakaTime.v18 directory within SMSS Extensions and make sure all files have been unblocked (right click -> properties). Then start SMSS as Admin, you can enter the API key from Tools -> WakaTime -> Settings but should be set if already using VS.

That works for me too

**Comment by michasacuer** [comment]
@odskee what do you mean by `properties -> unblock`?

**Comment by odskee** [comment]
@michasacuer In Windows File Explorer, you navigate to the actual WakaTime directory - select one or more, right click and properties and you'll likely see an option at the bottom to unblock (it's a tick box).  You'll often have this with downloaded files, just something to be aware of.

**Comment by gandarez** [comment]
Despite the error I launched a new version today please check it out https://github.com/gandarez/ssms-wakatime/releases/tag/v4.0.0

**Comment by alanhamlett** [comment]
Closing for now. Let us know if this is still not working and we can help debug it.
