### ISSUE TITLE
API Key's are too long for the fields to enter in SSMS 2018

### ISSUE THREAD

**Issue by RobRukavina** [wakatime/ssms-wakatime#33]
The only way I've found to work around this is to put the key in the field you access from vs code by pressing f1. Save that. (if you enter it from anywhere else in vs code extension settings it won't save and says it's invalid.) then reopen SSMS and the key is saved as it should be. I believe you can do this by adding the key to VS2022 extension as well and then opening SSMS. Nice to have a work around, but it would be even better if it just allowed the correct amount of characters to be input in the SSMS field and other vs code fields directly

**Comment by alanhamlett** [comment]
For now, try removing the `waka_` prefix from your api key. We'll release a new plugin update to fix this.

**Comment by RobRukavina** [comment]
will try that on Monday. Thank you!

**Comment by gandarez** [comment]
Just released a new version today to support `waka_`  prefix for Api Key.

https://github.com/gandarez/ssms-wakatime/releases/tag/v4.0.0

**Comment by alanhamlett** [comment]
Received a report that v4.1.0 is still not allowing api keys with the `waka_` prefix. It seems to be shortening/trimming the api key down to 36 characters.

**Comment by alanhamlett** [comment]
We're still limiting the max characters in the api key input field to 36, but with the new `waka_` prefix the api key length is 41:

https://github.com/wakatime/ssms-wakatime/blob/d786eddae08462f7518e6a897aff58e1edc5c78d/SSMS18/Forms/SettingsForm.Designer.cs#L64

**Comment by alanhamlett** [comment]
Fixed with 7a4b3634d22e9dcc6c197db9a230e17cdde56dc9. I increased it to 50, to give a little extra typing room since we already validate it using regex.

**Comment by gandarez** [comment]
Released a new version.
https://github.com/wakatime/ssms-wakatime/releases/tag/v4.1.1
