### ISSUE TITLE
The WakaTimePackage package does not install on SSMS v19.1

### ISSUE THREAD

**Issue by labilbe** [wakatime/ssms-wakatime#35]
HKCU registry part seems different of other versions.
![image](https://github.com/wakatime/ssms-wakatime/assets/54315/068dae82-b118-4a38-922c-e5ecaa58de9b)

I checked on `AddPackage.bat` and there is no handling of this case.
Is SSMS v19.x a handled version?

**Comment by labilbe** [comment]
Sorry, I didn't read docs :(

**Comment by wdemars** [comment]
I read and re-read the docs, but it's still failing for me. I'm getting a WakaTimePackage did not load correctly.

**Comment by rifkiamil** [comment]
@labilbe  > Sorry, I didn't read docs :(

I am looking for these documents. Where can I find them?

**Comment by labilbe** [comment]
> @labilbe > Sorry, I didn't read docs :(
> 
> I am looking for these documents. Where can I find them?

https://github.com/wakatime/ssms-wakatime#readme

**Comment by khayo** [comment]
to work properly in sms 19, its necessary to unblock all the files one by one 
![image](https://github.com/wakatime/ssms-wakatime/assets/4781909/0490d4f7-fd0a-4503-b921-37e13465cb6e)
